#!/bin/sh
# Usage: $1 <food id>
# See http://ndb.nal.usda.gov/ndb/search/list
curl -s 'http://ndb.nal.usda.gov/ndb/foods/show/'"$1"'?format=Full' | sed -e '/<a href="#id-[^"]*"><sup>/{N;d}' | sed -ne '/<td style="text-align:left;width:60px;" >/{N;N;N;N;N;N;N;N;N;N;N;N;N;s#	*<[^>]*>\([^\n]*\)\n.*center;width: 30px;">\([^<]*\)</td>\n	*<[^>]*>\([^<]*\)<.*#\1	\3\2#p}'
