#!/bin/bash
# Usage: $0 <friends> Ugnich
#        $0 <readers> Ugnich
curl -L -s "http://juick.com/$2/$1" | 
	Xtract-html '*//div[@id="content"]//a/@href' | 
		sed -e 's#//#/\n/#g' | 
			sed -e 's#/\(.*\)/$#\1#'
