#!/usr/bin/perl
use LWP::Simple;
use HTML::Entities;
use Data::Dumper;
use utf8;
binmode STDOUT, ":utf8";
$page=1;
$url="http://juick.com/$ARGV[0]/";
while (1) {
	$response = get("$url?page=$page");
	@posts = ($response =~ m#<li class="liav".*?</li>#sg);
	if ($#posts == -1) {
		print "All done!\n";
		exit 0;
	}
	foreach $post (@posts) {
		$post =~ m#<div class="msgnum">.*?">(.*?)</a></div>#s;
		print "$1 ";
		foreach $tag ($post =~ m#<a href="./\?tag=.*?">\*(.*?)</a>#sg) {
			print "*$tag ";
		}
		$post =~ m#<div class="msgtxt">(.*?)</div>#s;
		$body = $1;
		$body =~ s#<a href="http://juick.com/[0-9]*.*">(.*?)</a>#$1#sg;
		$body =~ s#<a href="(.*?)" rel="nofollow">.*?</a>#$1#sg;
		$body =~ s#<.*?>##sg;
		$body = decode_entities($body);
		print "\n$body\n";
		print "-"x80 . "\n";
	}
	$page++;
}
