#!/usr/bin/perl
use LWP::Simple;
use HTML::Entities;
use Data::Dumper;
use utf8;
binmode STDOUT, ":utf8";
$page=1;
$url="http://juick.com/$ARGV[0]/";
$before="9999999";
while (1) {
	$response = get("$url?before=$before");
	@posts = ($response =~ m#<li.*?class="msg">.*?</li>#sg);
	#print Dumper(@posts);
	if ($#posts == -1) {
		print "All done!\n";
		exit 0;
	}
	foreach $post (@posts) {
		$post =~ m#id="msg-([0-9]*)"#s;
		$before=$1;
		print "$1: ";
		map { print "*$_ " } ($post =~ m#\*<a href=".*?/\?tag=.*?">(.*?)</a>#sg);
		$post =~ m#<div class="msg-txt">(.*?)</div>#s;
		$body = $1;
		$body =~ s#<a href="http://juick.com/[0-9]*.*">(.*?)</a>#$1#sg;
		$body =~ s#<a href="(.*?)" rel="nofollow">.*?</a>#$1#sg;
		$body =~ s#<.*?>##sg;
		$body = decode_entities($body);
		print "\n$body\n";
		print "-"x80 . "\n";
	}
}
