#!/bin/sh
# Example: ./flibusta-massdownload http://flibusta.net/a/20828
curl "$@"|grep -Eo '/b/[0-9]+/fb2'|awk '{print "http://flibusta.net"$0}'|while read x; do
    #a=$(($RANDOM/1000+1))
    #echo "Sleeping for $a seconds."
    #sleep "$a"
    sturl="$(curl -i "$x"|awk '/^Location: .*/ {print $2}'|tr -d '\r\n')"
    echo "Getting $sturl"
    wget "$sturl"
done
