#!/bin/bash
baseurl="http://visionlabart.com"
page=1

collections=$(
	curl -s "${baseurl}/pages/all-artists" |
	sed -rn 's#.*href="/collections/([^"]*-art)".*#\1#p'
)
for coll in $collections; do
	mkdir $coll
	products=$(
		curl -s "${baseurl}/collections/${coll}?view=all" |
		sed -rn 's#.*href="/collections/.*-art/products/([^"]*)".*#\1#p' |
		sort -u
	)
	for prod in $products; do
		url=$(
			curl -s "${baseurl}/collections/${coll}/products/${prod}" |
			sed -rn 's#.*data-zoom-image="([^"]*)".*#https:\1#p'
		)
		echo "$coll/$prod"
		wget -q "$url" -O "$coll/${prod}.jpg"
	done 
done
