#!/bin/bash
baseurl="http://visionlabart.com/"
page=1
while :; do
	empty=1
	curl -s "${baseurl}collections/types?q=Fine%20Art&page=$i" |
	sed -rn 's#.*href="/(products[^"]*)".*#\1#p' |
	while read pgurl; do
		empty=0
		url=$(curl -s "${baseurl}/${pgurl}" |
			grep '<a.*id="mainImage"' |
			sed -rne 's#.*href="([^?"]*)[?"].*#http:\1#p')
		wget "$url"
	done
	[[ "$empty" == "1" ]] && break
done
