#!/bin/bash
# Usage: $0 <url of the album to download>
for u in $(for pu in "$1" `curl -s "$1" | grep b-pager__current | tr \> '\n' | sed -ne 's#.*href="\([^"]*\)".*#\1#p'`; do
		curl -s "$pu" | sed -ne 's#.*class="photo" href="\([^"]*view/[0-9][^"]*\)".*#\1#p'
			done); do
	wget -c "`curl -s "http://fotki.yandex.ru$u" | sed -ne 's#.*href="\([^"]*_orig\)">.*#\1#p'`"
done
