#!/bin/bash
# Usage: $0 <from> <to> [<when>]
[[ -z "$3" ]] && when='%D0%BD%D0%B0+%D0%B2%D1%81%D0%B5+%D0%B4%D0%BD%D0%B8' || when=`echo -n "$3" | urlencode`
curl -s "http://rasp.yandex.ru/search/?fromName=`echo -n "$1" | urlencode`&toName=`echo -n "$2" | urlencode`&when=$when" | sed -e '/^ *$/d' | sed -n -e '/            <a class="b-link" /{N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;s#.*station_from=[0-9]*">\([0-9]*\) <[^>]*>\([^<]*\)<.*nowrap">\([^<]*\).*departure[^"]*">[^>]*>[^>]*>\([^<]*\)<.*js-datetime[^>]*>\([^<]*\)<.*__days[^>]*>\([^<]*\)<.*#\1\t\2\t\3\t\4\t\t\5\t\6#p}'
