#!/usr/bin/perl
use utf8;
use URI::Escape;
use LWP::Simple;
use Encode;
use HTML::Entities;

binmode STDOUT, ':utf8';
$ARGV[1] ||= 20;
$page=decode_utf8(get("http://yandex.ru/yandsearch?text=".uri_escape_utf8(decode_utf8($ARGV[0]))."&numdoc=".$ARGV[1]."&lr=42"));
while ($page=~/<a class=\"b-serp-item__title-link\" tabindex=\"2\" href=\"([^\"]+)\" onmousedown[^>]+>(.+?)<\/a>/gsi) {
	$post=decode_entities($1.$2);
	$post=~s/(<[^>]*>| )+/ /gsi;
	$post=~s/\n\s+/\n/gsi;
	print $post."\n";
}
