#!/bin/sh
tok=202055f2976f4cbd936c2f13de990cc4
for i in `curl -s "https://api.mailinator.com/api/inbox?to=$1&token=$tok" | jq -r '.messages[].id'`; do
	curl -s "https://api.mailinator.com/api/email?msgid=$i&token=$tok" | jq -r '"Subject: " + .data.subject, .data.parts[].body'
done
