#!/bin/sh

#  Copyright (c) 2011, Alexander Batischev
#  All rights reserved.

clBold="`echo '\033[1m'`"
clReset="`echo '\033[m'`"

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 ${clBold}title${clReset}"
    echo "       $0 ${clBold}readmanga URL${clReset}"

    exit
fi

if [ -z "`echo \"$1\" | grep 'readmanga\.ru'`" ]
then
    urls="`readmangasearch \"$*\"`"
    if [ -z "$urls" ]
    then
        exit
    else
    if [ "`echo \"$urls\" | wc -l`" -ne "1" ]
    then
        echo "There are few mangas that satisfy your query:\n"
        echo "$urls"
        echo "\nPlease choose one and give a URL as a parameter to ${0}"
        # TODO: enumerate found URLs and let user choose
        exit
    fi
    fi
else
    urls="$1"
fi

url="$urls"

# mature=1 means reader is 18 years old or above
page="`curl -s \"$url?mature=1\"`"

mangaTitle="`echo \"$page\" | grep -A 2 'leftContent' | tr -d "\n\r" | sed -r 's#.*<div class="leftContent"> +<h1>(<span.*">|)Манга(</span>|) (.*)</h1>.*#\3#; s# +# #g; s#\((.*)\)#/ \1#; s# $##'`"
rateInfo="`echo \"$page\" | grep -A 2 'rate_info' | tr -d "\n\r" | sed -r 's#.*<p class="smallText rate_info">.*Рейтинг: <b>([^<]+)</b>.*Всего голосов: <b>([0-9]+).*#\1 (\2 голосов)#'`"
volumesInfo="`echo \"$page\" | grep -A 2 'Томов:' | tr -d "\n\r" | sed -r 's#.*<b>Томов:</b> +([0-9]+).*#\1#'`"
translationStatus="`echo \"$page\" | grep -A 3 'Перевод:' | tr -d "\n\r" | sed -r 's#.*<p><b>Перевод:</b> +(.*) +</p>.*#\1#; s# +$##'`"
genres="`echo \"$page\" | grep '/genre/' | tr -d "\n\r" | sed -r 's#<a href="[^"]+">([^<]*)</a>#\1#g; s# +# #g'`"
author="`echo \"$page\" | grep '/author/' | sed -r 's#.*<a.*>(.*)</a>#\1#' | tr "\n\r" " "`"
translators="`echo \"$page\" | grep translator | sed -r 's#.*<a href="([^"]*)">([^<]*)</a>.*#  • \2 ( http://readmanga.ru\1 )#;' | urldecode`"
description="`echo \"$page\" | tr -d "\n\r" | sed -r 's#.*<div class="mangaDescription">(.*)#\1#; s# *Описание *##; s#Редактировать описание</a>.*##; s#<em>(.*)</em>#\n\n\1#; s#<br(/| /|)>#\n#g; s#<[^>]*>##g; s# +# #g; s# $##; s#\s+Редактировать описание.*##' | htmldecode`"

echo "${clBold}${mangaTitle}${clReset}"
echo "${clBold}${author}${clReset}\n"

echo "$url?mature=1\n"

echo "${clBold}Рейтинг:${clReset} $rateInfo"
echo "${clBold}Жанры:${clReset}${genres}"
if [ -n "$volumesInfo" ];
then echo "${clBold}Томов:${clReset} $volumesInfo"
fi
echo "${clBold}Перевод:${clReset} $translationStatus"
echo "${clBold}Переводчик(и):${clReset}\n${translators}\n"

echo "${clBold}Описание${clReset}:\n$description\n"

