#!/bin/sh

#  Copyright (c) 2011, Alexander Batischev
#  All rights reserved.

clBold="`echo '\033[1m'`"
clReset="`echo '\033[m'`"

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 ${clBold}title${clReset}"
    echo "       $0 ${clBold}readmanga URL${clReset}"

    exit
fi

if [ -z "`echo \"$1\" | grep 'readmanga\.ru'`" ]
then
    urls="`readmangasearch \"$*\"`"
    if [ "`echo \"$urls\" | wc -l`" -eq "1" ]
    then
        url="$urls"
    else
        # readmangaget relies upon exact match with that line
        echo "There are few mangas that satisfy your query:\n"
        echo "$urls"
        echo "\nPlease choose one and give a URL as a parameter to ${0}"
        # TODO: enumerate found URLs and let user choose
        exit
    fi
else
    url="$*"
fi

# mature=1 means reader is 18 years old or above
page="`curl -s \"$url?mature=1\"`"

echo "$page" | egrep ' {16}<a href=".*/vol' | sed -r 's#<a href="(.*)" title.*>(.*)</a>#\2\t\1#; s#^ +##; s#(.*)\t(.*)#http://readmanga.ru\2\t\1#' | tac

