#!/bin/sh

#  Copyright (c) 2011, Alexander Batischev
#  All rights reserved.

clBold="`echo '\033[1m'`"
clReset="`echo '\033[m'`"

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 ${clBold}title${clReset}"

    exit
fi

query="`echo -n \"$*\" | urlencode`"

page="`curl -s -d \"q=${query}\" \"http://readmanga.ru/search\"`"
echo "$page" | tr -d "\n\r" | grep -o '<div id="mangaResults">.*</table>' | sed 's#<#\n<#g' | egrep '(a href|<span)' | tr -d "\n\r" | sed 's#<a#\n<a#g' | sed -r 's#<a href="(.*)" title=".*#http://readmanga.ru\1#g' | grep -v '^$'
