#!/bin/sh

#  Copyright (c) 2011, Alexander Batischev
#  All rights reserved.

clBold="`echo '\033[1m'`"
clReset="`echo '\033[0m'`"

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 title"
    echo "       $0 -a author"
    
    exit
fi

if [ "$1" = "-a" ]
then
    shift
    author="`echo \"$*\" | urlencode`"
    page="`curl -s \"http://anymanga.com/search/?query=${author}&type=author\"`"
else
    title="`echo \"$*\" | urlencode`"
    page="`curl -s \"http://anymanga.com/search/?query=${title}&type=manga\"`"
fi

results=`echo "$page" | grep span | grep -v '<td colspan=3 style="padding: 5px 0 0 5px;">' | grep -v 'padding: 0' | grep -v 'font-weight: normal' | tr "\r" "\n" | tr -d "\n" | sed "s#</span>#\n#g" | sed -r "s#.*href=\"(.*)\" > (.*)</a> by (.*)#${clBold}\2${clReset} by ${clBold}\3${clReset}:\nhttp://anymanga.com\1\n#"`
if [ -n "$results" ]
then
    echo "$results"
fi

