#!/bin/sh

#  Copyright (c) 2011, Alexander Batischev
#  All rights reserved.

clBold="`echo '\033[1m'`"
clReset="`echo '\033[m'`"

fetchChapter() {
    title="$1"
    volume="$2"
    chapter="$3"

    page="`curl -s \"http://anymanga.com/$title/$volume/$chapter\"`"
    pageNames="`echo \"$page\" | grep pagelist | head -1 | sed 's#show_pagelist(\[##;  s#\],.*$##' | tr -d "' "`"
    pages="`curl -s \"http://anymanga.com/$title/$volume/$chapter/{${pageNames}}\"`"

    if [ -n "$pages" ]
    then
        mkdir "$chapter"
        cd "$chapter"

        echo "$pages" | grep img | grep "$title" | sed -r 's#<img src="(.*)" title.*#\1#;  s#^#http://anymanga.com#' > urls

        wget --continue --input=urls
        rm -f urls

        cd ..
    fi
}

fetchVolume() {
    title="$1"
    volume="$2"

    page="`curl -s \"http://anymanga.com/$title/\"`"
    chapters="`echo \"$page\" | grep \"/$title/$volume\" | grep '<li>' |
        sed -r 's#.*a href="(.*)" >.*#\1#;  s#/[^/]+/[^/]+/([^/]+)/#\1#'`"
    if [ -n "$chapters" ]
    then
        mkdir "$volume"
        cd "$volume"

        for chapter in $chapters
        do
            fetchChapter "$title" "$volume" "$chapter"
        done

        cd ..
    fi
}

fetchTitle() {
    title="$1"

    page="`curl -s \"http://anymanga.com/$title/\"`"
    volumesAndChapters="`echo \"$page\" | grep \"/$title\" | grep '<li>' | sed -r 's#.*a href="(.*)" >.*#\1#;  s#/[^/]+/(.*)/#\1#'`"

    if [ -n "$volumesAndChapters" ]
    then
        mkdir "$title"
        cd "$title"

        for i in $volumesAndChapters
        do
            volume="`dirname $(echo \"$i\")`"
            chapter="`basename $(echo \"$i\")`"
            mkdir "$volume"
            cd "$volume"
            fetchChapter "$volume" "$volume" "$chapter"
            cd ..
        done
       

        cd ..
    fi
}

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 ${clBold}title${clReset} [${clBold}volume${clReset} [${clBold}chapter${clReset}]]"
    echo "       $0 ${clBold}URL${clReset}"

    exit
fi

if [ -z "`echo \"$1\" | grep 'anymanga\.com'`" ]
then
    title="$1"
    volume="$2"
    chapter="$3"
else
    # we were given a URL; now let's parse it
    url="`echo \"$1\" | sed 's#^http://##'`"

    title="`echo \"$url\" | sed -r 's#[^/]+/([^/]+).*#\1#'`"

    volume="`echo \"$url\" | sed -r 's#[^/]+/[^/]+/([^/]+).*#\1#'`"
    if [ "$volume" = "$url" ]
    then
        volume=""
    fi

    chapter="`echo \"$url\" | sed -r 's#[^/]+/[^/]+/[^/]+/([^/]+).*#\1#'`"
    if [ "$chapter" = "$url" ]
    then
        chapter=""
    fi
fi

if [ -n "$chapter" ]
then
    fetchChapter "$title" "$volume" "$chapter"
else
    if [ -n "$volume" ]
    then
        fetchVolume "$title" "$volume"
    else
        fetchTitle "$title"
    fi
fi

