#!/bin/bash
if [[ -n "$1" ]]; then
	f="$1"
else
	f="`tempfile`"
	trap 'rm "$f"' EXIT
	cat > "$f"
fi
curl -w %{redirect_url} -F "file=@\"$f\"" https://dump.bitcheese.net/upload-file?simple | sed -e 's#http#https#'
echo
