#!/bin/bash
c="`tempfile`"
trap "rm $c" EXIT
ua='Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.12) Gecko/20101028 Firefox/3.6.12'
u="`urlencode <<< "$1"`"
curl -A "$ua" -c "$c" "http://savefrom.net/$1" -s > /dev/null
curl -s -A "$ua" -b "$c" 'http://en.savefrom.net/savefrom.php' -d "sf_url=$u&sf_submit.x=0&sf_submit.y=0" | tr -d \\n | 
# Wasted half an hour on this crazy shit
sed -e 's/.*eval(unescape(\([^)]*\)).*/print(unescape(\1));/' | js | 
	sed -e 's/.*>\(var[^<]*\)<.*/\1/;s/\;var s=document.*tex/\;/;s/eval(\([^;]*\))\;.*$/\1\;'\''\;print(t);/' | js | 
		sed -e 's#window\['\''\\x65\\x76\\x61\\x6c'\''\](f)#print(f)#' | js | 
			sed -e 's/eval/print/' | js | 
				perl -ne 's#.*?{"url":"([^"]*)".*#\1#g and print' | sed -e 's#\\\/#/#g'
