#!/bin/sh

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 ${clBold}query${clReset}"
    echo "       $0 ${clBold}prostopleer URL${clReset}"
    exit
fi

curl -s -c /tmp/cookies "http://prostopleer.com" >/dev/null
if [ -n "`echo \"$*\" | grep 'prostopleer.ru'`" ]
then
    # we've got download link, simply play it!
    urls="$*"
else
    urls="`prostosearch \"$*\"`"
fi

if [ -z "$urls" ]
then
    exit
fi

for url in $urls
do
    mplayer -cache 50 -prefer-ipv4 -cookies -cookies-file /tmp/cookies "$url"
done

rm -f /tmp/cookies

