#!/bin/sh

#  Copyright (c) 2011, Alexander Batischev, Sergey Alirzaev
#  All rights reserved.
#  
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  
#   o  Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   o  Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#
#   o  Neither the name of the copyright holder nor the names of
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
#  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
#  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
#  WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE

clBold="`echo '\033[1m'`"
clReset="`echo '\033[m'`"

if [ -z "$1"  -o  "$1" = "-h" ]
then
    echo "Usage: $0 ${clBold}URL${clReset}"
    echo
    echo "       If someone gave you a link to a song (something like"
    echo "       http://prostopleer.com/tracks/276374yAW0 ), use this"
    echo "       script to get direct URL to a file."
    exit 1
fi

if [ -z "`echo \"$1\" | grep 'prostopleer\.com'`" ]
then
    echo "Given URL don't seem to belong to 'prostopleer.com' domain!"
    exit 1
fi

# getting cookies
curl -s -c cookies "http://prostopleer.com" >/dev/null

fileIDs="`curl -s -b cookies -c cookies \"$1\" | sed 's#<#\n<#g' | grep file_id | sed -r 's#.*file_id="(.*)" singer.*#\1#'`"

if [ -z "$fileIDs" ]
then
    rm -f cookies
    exit 1
fi

(
    curl -s http://prostopleer.com/js/nanoplayer.min.js | sed -e 's/^.*getFilePath:\(.*\),fixHash:.*$/var g=\1;/'
    for id in $fileIDs
    do
        echo "print('http://prostopleer.ru' + g(\"$id\"));"
    done
) | js

rm -f cookies

