#!/bin/bash
if [[ -n "$2" ]]; then
	out=`vkfindaudio-api "$1" < ~/.config/vkbash | egrep "$2"`
else
	out=`vkfindaudio-api "$1" < ~/.config/vkbash`
fi
echo $out
mpv `egrep -o 'http[^ ]*\.mp3' <<< $out`
