#!/bin/bash
st="$1"
shift
if [[ -n "$1" ]]; then
	out=`vkfindaudio-w3m "$st" < ~/.config/vkbash | grep "$@"`
else
	out=`vkfindaudio-w3m "$st" < ~/.config/vkbash`
fi
echo $out
mpv `egrep -o 'http[^ ]*\.mp3' <<< $out`
