#!/bin/bash
# Usage: $0 cookies terms
t="`tempfile`"
trap "rm \"$t\"" EXIT
find="`echo -n "$2" | urlencode`"
offset=0
result=1
while test $result = 1; do
	curl -LsS -d "act=search&al=1&from=pad&offset=$offset&performer=0&q=$find" -b "$1" http://vk.com/audio > "$t"
	iconv -f cp1251 "$t" | sed -n -e '/input/{N;N;N;s#.*value="\([^,]*\),.*return false">\(.*\)</div>.*#\1\t\2#;s#</*span[^>]*>##g;s#</a></b>##;p}' | htmldecode
	result="`tail -n 1 "$t" | sed 's#.*has_more":\([^,]\),.*#\1#'`"
	offset="`tail -n 1 "$t" | sed 's#.*searchOffset":\([^,]*\),.*#\1#'`"
done
