#!/bin/bash
# Usage: $0 https://vk.com/videos-64075933
file="`tempfile`"
trap "rm $file" EXIT
ua=firefox
oid="`echo "$1" | sed -e 's#.*videos-##'`"
for vid in `curl -sLA "$ua" "$1" | sed -ne 's#.*video_cont-\([^"]*\)".*#\1#p'`; do
	curl --retry 3 --retry-delay 5 --connect-timeout 4 -sLA "$ua" "$1?z=video-$vid/club$oid" | sed -ne 's#.*<source src="\([^"]*\)".*#\1#p'
done
