#!/bin/bash
LOGIN=$1
PASSWORD=$2
COOKIEF=$3

wget -S --save-cookies "$COOKIEF" --keep-session-cookies --post-data="success_url=&fail_url=&try_to_login=1&email=$LOGIN&pass=$PASSWORD" 'http://vk.com/login.php' -O /dev/null -q &> /dev/null

