#!/bin/bash
fn=`tempfile -p vkbashcookies`
trap 'rm "$fn";' EXIT
umask 0077
read login password
wget --save-cookies "$fn" "https://login.vk.com/?act=login" --post-data "email=`printf %s "$login" | urlencode`&pass=`printf %s "$password" | urlencode`" -O /dev/null 2> /dev/null
at="$(wget --load-cookies "$fn" "http://oauth.vk.com/authorize?client_id=3082784&scope=audio&redirect_uri=http://oauth.vk.com/blank.html&display=wap&response_type=token" --post-data='submit=Разрешить' -O /dev/null 2>&1 | grep "access_token" | cut -d "=" -f2 | cut -d "&" -f1)"

dbg() {
	true
	#echo "$@" 1>&2
}

api() {
	dbg ">>>> api request $1"
	resp="$(curl -sS -c "$fn" "https://api.vk.com/method/$1")"
	dbg "<<<< $(jq . <<< "$resp")"
	echo -n "$resp"
}

while [ -f "$1" ]; do
	t="$(api "audio.getUploadServer?access_token=${at}" | jq -r '.response.upload_url')"
	[ -z "$t" -o "$t" == null ] && {
		exit 1
	}

	dbg ">>>> upload file to $t"
	t="$(curl -sS -c "$fn" -F "file=@$1" "$t")"
	dbg "<<<< $(jq . <<< "$t")"
	p_server=$(jq -r '.server' <<< "$t")
	p_audio=$(echo -n "$(jq -r '.audio' <<< "$t")" | urlencode)
	p_hash=$(jq -r '.hash' <<< "$t")
	
	t="$(api "audio.save?server=${p_server}&audio=${p_audio}&hash=${p_hash}&access_token=${at}")"
	err="$(jq -r '.error.error_msg' <<< "$t")"
	[ "$err" != null ] && {
		echo "$err" 1>&2
		exit 1
	}
	jq -r '.response.url' <<< "$t"
	shift
done
