#!/bin/bash
. $(dirname $(which "$0"))/vkapi.sh

auth audio

while [ -f "$1" ]; do
	t="$(api "audio.getUploadServer?access_token=${at}" | jq -r '.response.upload_url')"
	[ -z "$t" -o "$t" == null ] && {
		exit 1
	}

	dbg ">>>> upload file to $t"
	t="$(curl -sS -c "$fn" -F "file=@$1" "$t")"
	dbg "<<<< $(jq . <<< "$t")"
	p_server=$(jq -r '.server' <<< "$t")
	p_audio=$(echo -n "$(jq -r '.audio' <<< "$t")" | urlencode)
	p_hash=$(jq -r '.hash' <<< "$t")
	
	t="$(api "audio.save?server=${p_server}&audio=${p_audio}&hash=${p_hash}&access_token=${at}")"
	err="$(jq -r '.error.error_msg' <<< "$t")"
	[ "$err" != null ] && {
		echo "$err" 1>&2
		exit 1
	}
	jq -r '.response.url' <<< "$t"
	shift
done
