#!/usr/bin/env bash

query=`echo $1 | tr ' ' '+'`
porn_pages=`curl -sL "http://www.youporn.com/search/relevance/?category_id=0&type=straight&page=1&query="$query | grep -E "videoTitle.*watch" | cut -f 3 -d "/"`


for i in `echo $porn_pages | tr ' ' '\n'`; do
    curl -sL 'http://youporn.com/watch/'$i | grep '$video.src' | uniq | sed -e "s|\$video.src = '||;s|'\;||"
done
