#!/bin/bash
# Usage: $0 https://waterflame.newgrounds.com/audio/
for u in $(curl -s "$1" | sed -n -e 's,.*<a href="\([^"]*/\)listen\(/[^"]*\)".*,https:\1download\2,p'); do
	relu="$(curl -v "$u" 2>&1 | sed -ne 's,.*location: \(https.*\),\1,p')"
	while [[ -z "$relu" ]]; do
		echo Downloading too fast, waiting... >&2
		sleep 30
		relu="$(curl -v "$u" 2>&1 | sed -ne 's,.*location: \(https.*\),\1,p')"
	done
	fn="$(echo "$relu" | cut -d / -f 5- | cut -d \? -f 1)"
	wget -c "$relu" -O "$fn"
done
