#!/bin/sh
for f in "$@"; do
	if ! mime=$(file -Eb --mime-type "$f"); then
		echo "$mime"
		exit 1
	fi
	curl https://tinystash.undef.im/upload/file -H app-id:"${W3CRAPCLI_TINYSTASH_APP_ID:-w3crapcli}" -H content-type:"$mime" --data-binary @"$f" | sed -e "s,$,.${f##*.},"
done
